packages:
  - 'packages/tb-shared'
  - 'packages/tb-frontend'
  - 'packages/tb-nest'
  - 'packages/s-shared'
  - 'packages/s-frontend'
  - 'packages/s-nest'
  - 'packages/sansa-x'

catalog:
  # Build tools
  vite: ^5.4.19
  vitest: ^3.1.4
  typescript: ^5.2.2
  'vite-plugin-dts': ^4.5.4

  # React
  react: ^19.1.0
  'react-dom': ^19.1.0
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.0
  '@vitejs/plugin-react': ^4.3.4

  # ESLint
  eslint: ^9.27.0
  '@eslint/js': ^9.27.0
  '@typescript-eslint/eslint-plugin': ^8.32.1
  '@typescript-eslint/parser': ^8.32.1
  'eslint-plugin-react-hooks': ^5.2.0
  'eslint-plugin-react-refresh': ^0.4.9
  'eslint-config-prettier': ^10.1.1
  'eslint-plugin-prettier': ^5.2.6

  # Styling
  tailwindcss: ^3.4.1
  postcss: ^8.4.35
  autoprefixer: ^10.4.17

  # Utilities
  '@types/node': ^20.9.0
  concurrently: ^8.2.2
  jsdom: ^26.1.0
